[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.12"
dependencies = [
    "asgiref==3.10.0",
    "attrs==25.4.0",
    "autobahn==25.10.2",
    "automat==25.4.16",
    "blinker==1.9.0",
    "cattrs==25.3.0",
    "certifi==2025.10.5",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "click==8.3.1",
    "constantly==23.10.4",
    "contourpy==1.3.3",
    "cryptography==46.0.3",
    "cycler==0.12.1",
    "dash==3.3.0",
    "dash-bootstrap-components==2.0.4",
    "django==5.2.7",
    "django-bootstrap5==25.2",
    "django-cors-headers==4.9.0",
    "django-currentuser==0.9.0",
    "django-stubs==5.2.7",
    "django-stubs-ext==5.2.7",
    "django-tastypie==0.15.1",
    "djangorestframework==3.16.1",
    "dotenv==0.9.9",
    "dpd-components==0.2.0",
    "flask==3.1.2",
    "flatbuffers==25.9.23",
    "fonttools==4.60.1",
    "h11==0.16.0",
    "hyperlink==21.0.0",
    "idna==3.11",
    "importlib-metadata==8.7.0",
    "incremental==24.7.2",
    "itsdangerous==2.2.0",
    "jh2==5.0.10",
    "jinja2==3.1.6",
    "kiwisolver==1.4.9",
    "markupsafe==3.0.3",
    "matplotlib==3.10.7",
    "msgpack==1.1.2",
    "narwhals==2.11.0",
    "nest-asyncio==1.6.0",
    "niquests==3.15.2",
    "numpy==2.3.4",
    "openmeteo-requests==1.7.4",
    "openmeteo-sdk==1.23.0",
    "packaging==25.0",
    "pandas==2.3.3",
    "pillow==12.0.0",
    "platformdirs==4.5.0",
    "plotly==6.4.0",
    "psycopg==3.2.12",
    "psycopg2-binary>=2.9.11",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.2",
    "pycparser==2.23",
    "pyopenssl==25.3.0",
    "pyparsing==3.2.5",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.1",
    "python-mimeparse==2.0.0",
    "pytz==2025.2",
    "pyyaml==6.0.3",
    "qh3==1.5.6",
    "requests==2.32.5",
    "requests-cache==1.2.1",
    "retry-requests==2.0.0",
    "retrying==1.4.2",
    "service-identity==24.2.0",
    "setuptools==80.9.0",
    "six==1.17.0",
    "sqlparse==0.5.3",
    "twisted==25.5.0",
    "txaio==25.9.2",
    "types-pyyaml==6.0.12.20250915",
    "typing-extensions==4.15.0",
    "tzdata==2025.2",
    "url-normalize==2.2.1",
    "urllib3==2.5.0",
    "urllib3-future==2.14.908",
    "wassima==2.0.2",
    "weasyprint>=69.0",
    "werkzeug==3.1.3",
    "zipp==3.23.0",
    "zope-interface==8.1.1",
]
