# Generated by Django 5.2.7 on 2025-11-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='nickname',
            field=models.CharField(default='device', max_length=100),
        ),
    ]
