# Generated by Django 5.2.7 on 2026-02-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_device_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="data",
            options={"ordering": ["date"]},
        ),
    ]
