# Generated by Django 5.2.7 on 2026-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_data_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="pressure",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="temp",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="data",
            name="uv",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="wind_speed",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
