# Generated by Django 5.2.7 on 2026-06-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_data_pressure_alter_data_temp_alter_data_uv_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="pressure",
        ),
        migrations.RemoveField(
            model_name="data",
            name="uv",
        ),
        migrations.RemoveField(
            model_name="data",
            name="wind_direction",
        ),
        migrations.RemoveField(
            model_name="data",
            name="wind_speed",
        ),
    ]
